#!/usr/bin/env bash

SUM=0

arg-count(){
    # write out the arguments we got
    echo $#
    SUM=$(($SUM+$#))
}

for file in * ; do
   arg-count $file
done

echo "Total number of arguments: $SUM"
echo "Total number of files: " `ls | wc -l`
